[package]
name = "dbg-generate-sata-wal-from-pcap"
description = "A tool that can generate a SATA WAL log from a PCAPNG."
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true
# This is a debugging tool for us, it doesn't need to live on CRATES.io
publish = false

[dependencies]
bytes.workspace = true
cat-dev = { default-features = false, features = ["servers"], path = "../../pkg/cat-dev" }
clap.workspace = true
fnv.workspace = true
miette.workspace = true
rm-lisa.workspace = true
rtshark = "^3.2.0"
tokio.workspace = true
tracing.workspace = true
valuable.workspace = true