[workspace]
members = [
  "cmd/bridgectl",
  "cmd/catlog",
  "cmd/dbg-generate-sata-wal-from-pcap",
  "cmd/findbridge",
  "cmd/getbridgeconfig",
  "cmd/mionps",
  "cmd/mionparamspace",
  "cmd/pcfsserver",
  "cmd/setbridgeconfig",
  "pkg/cat-dev",
  "pkg/log",
]
resolver = "3"

[workspace.dependencies]
bytes = "^1.10.1"
clap = { version = "^4.5.40", features = ["color", "derive", "env", "error-context", "help", "suggestions", "unicode", "usage", "wrap_help"] }
fnv = "^1.0.7"
futures = "^0.3.31"
mac_address = "^1.1.8"
miette = { version = "^7.6.0", features = ["fancy"] }
network-interface = "^2.0.1"
time = "^0.3.41"
tracing = { version = "^0.1.41", features = ["valuable"] }
tokio = { version = "^1.45.1", features = ["full", "tracing"] }
valuable = { version = "^0.1.1", features = ["derive"] }

[workspace.package]
authors = ["Cynthia <cynthia@coan.dev>"]
edition = "2024"
license = "MIT"
repository = "https://github.com/rem-verse/sprig"
version = "0.0.11"

[profile.release]
codegen-units = 1
opt-level = 3
lto = "fat"
panic = "abort"
split-debuginfo = "packed"
strip = "none"
