//! Just a list of all the exit codes in our process.

pub const NOT_YET_IMPLEMENTED: i32 = 1;
pub const LOGGING_HANDLER_INSTALL_FAILURE: i32 = 2;
pub const SHOULD_NEVER_HAPPEN_FAILURE: i32 = 3;
pub const FAILED_TO_WRITE_TO_DISK: i32 = 4;
pub const BRIDGE_TOO_OLD_FOR_FEATURE: i32 = 5;
pub const HOST_FILESYSTEM_INIT_FAILURE: i32 = 6;

pub const ARGV_PARSE_FAILURE: i32 = 10;
pub const ARGV_NO_COMMAND_SPECIFIED: i32 = 11;
pub const ARGV_BRIDGE_CONFLICTING_ARGUMENTS: i32 = 12;
pub const ARGV_NO_BRIDGE_ENV: i32 = 13;
pub const ARGV_NO_BRIDGE_SPECIFIED: i32 = 14;
pub const ARGV_COULD_NOT_SEARCH_FOR_BRIDGE: i32 = 15;
pub const ARGV_NO_BRIDGE_STATE_PATH: i32 = 16;
pub const ARGV_BRIDGE_STATE_LOAD_FAILURE: i32 = 17;
pub const ARGV_COULD_NOT_GET_DEFAULT_BRIDGE: i32 = 18;
pub const ARGV_SERIAL_CONFLICTING_ARGUMENTS: i32 = 19;
pub const ARGV_NO_FSEMUL_PATH: i32 = 20;
pub const ARGV_FSEMUL_LOAD_FAILURE: i32 = 21;
pub const ARGV_NO_CAFE_ROOT: i32 = 22;
pub const ARGV_CAFE_ROOT_LOAD_FAILURE: i32 = 23;

pub const SERIAL_PORT_CONNECTION_FAILURE: i32 = 25;

pub const ADD_COULD_NOT_UPSERT: i32 = 30;
pub const ADD_COULD_NOT_SAVE_TO_DISK: i32 = 31;

pub const BOOT_CGI_FAILURE: i32 = 35;
pub const BOOT_NOT_READY_TO_BOOT: i32 = 36;
pub const BOOT_COULD_NOT_CONNECT: i32 = 37;
pub const BOOT_FSEMUL_SERVER_ERROR: i32 = 38;
pub const BOOT_COULD_NOT_SPAWN: i32 = 39;

pub const DUMP_PARAMS_FAILED_TO_GET_PARAMS: i32 = 40;

pub const GET_FAILED_TO_SEARCH_FOR_DEVICE: i32 = 45;
pub const GET_FAILED_TO_FIND_SPECIFIC_DEVICE: i32 = 46;

pub const GET_PARAMS_NO_PARAMETERS_SPECIFIED: i32 = 50;
pub const GET_PARAMS_FAILED_TO_GET_PARAMS: i32 = 51;

pub const LIST_COULD_NOT_SEARCH: i32 = 55;

pub const LSSP_FAILED_ENUMERATION: i32 = 60;
pub const LSSP_NO_PORTS: i32 = 61;

pub const REMOVE_BRIDGE_DOESNT_EXIST: i32 = 65;
pub const REMOVE_COULD_NOT_SAVE_TO_DISK: i32 = 66;

pub const SET_DEFAULT_BRIDGE_DOESNT_EXIST: i32 = 70;
pub const SET_DEFAULT_COULD_NOT_SAVE_TO_DISK: i32 = 71;

pub const SET_PARAMS_NO_PARAMETERS_SPECIFIED: i32 = 75;
pub const SET_PARAMS_INVALID_PARAMETER_SET_STRING: i32 = 76;
pub const SET_PARAMS_INVALID_PARAMETER_VALUE: i32 = 77;
pub const SET_PARAMS_FAILED_TO_SET_PARAMS: i32 = 78;

pub const TAIL_COULD_NOT_SPAWN: i32 = 80;
pub const TAIL_NO_SERIAL_PORT: i32 = 81;

pub const DUMP_EEPROM_FAILURE: i32 = 85;

pub const DUMP_MEMORY_FAILURE: i32 = 90;

pub const DECRYPT_FW_BAD_OUTPUT_PATH: i32 = 95;
pub const DECRYPT_FW_COULD_NOT_READ_FW: i32 = 96;
pub const DECRYPT_FW_COULD_NOT_DECRYPT_FW: i32 = 97;
pub const DECRYPT_FW_COULD_NOT_WRITE_FW: i32 = 98;

pub const ENCRYPT_FW_BAD_OUTPUT_PATH: i32 = 100;
pub const ENCRYPT_FW_COULD_NOT_READ_FW: i32 = 101;
pub const ENCRYPT_FW_COULD_NOT_ENCRYPT_FW: i32 = 102;
pub const ENCRYPT_FW_COULD_NOT_WRITE_FW: i32 = 103;
