---
name: Bug Report with Built/Installed Tools
description: File a bug report about issues using already built/installed tools
title: "[Tool Bug]: "
labels: ["bug", "triage"]
projects: []
assignees:
  - mythra
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

        Please also set the environment variable `SPRIG_LOGGING=info,bridgectl=debug,cat_dev=debug`
        for the most helpful information in logs. This will produce a lot of logging information that's
        very helpful for us!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: What version of our software are you running (`bridgectl --version`)?
    validations:
      required: true
  - type: dropdown
    id: host-os
    attributes:
      label: What host-os are you running on?
      multiple: true
      options:
        - Windows
        - macOS
        - Linux (any flavour)
        - BSD (any flavour)
        - Other Nix Based System
        - Other Non Nix, or non BSD based OS
  - type: input
    id: target
    attributes:
      label: Target Device
      description: If talking to a device (e.g. a cat-dev/cat-r) please list the device + it's version here.
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/rem-verse/sprig/blob/trunk/.github/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
