---
name: Bug Report with Development Library
description: File a bug report about any of the libraries we publish for others to use
title: "[Library Bug]: "
labels: ["bug", "triage"]
projects: []
assignees:
  - mythra
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-is-the-issue
    attributes:
      label: What is the issue?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "Your library is doing something wrong!"
    validations:
      required: true
  - type: input
    id: package
    attributes:
      label: Package
      description: What package are you running into an issue with?
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: What version of the package did you experience the bug in?
    validations:
      required: true
  - type: input
    id: features
    attributes:
      label: Features
      description: If using a library, what features have you enabled/disabled if you are not using the default?
    validations:
      required: false
  - type: dropdown
    id: host-os
    attributes:
      label: What host-os are you using?
      multiple: true
      options:
        - Windows
        - macOS
        - Linux (any flavour)
        - BSD (any flavour)
        - Other Nix Based System
        - Other Non Nix, or non BSD based OS
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/rem-verse/sprig/blob/trunk/.github/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
